name: Gradle CI

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build with gradle

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2.3.1
        with:
          distribution: temurin
          java-version: 17
          java-package: jdk
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle/loom-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: easy_commands-1.20.2-artifacts
          path: build/libs/*.jar
